language: ruby
rvm:
  - 2.2
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
notifications:
  email:
    on_success: always
    on_failure: always

# install:
#  - sudo apt-get install libqt4-dev
#  - pip install PySide --no-index --find-links https://<your-site>;
#  # Travis CI servers use virtualenvs, so we need to finish the install by the following
#  - python ~/virtualenv/python${TRAVIS_PYTHON_VERSION}/bin/pyside_postinstall.py -install

# ver: https://github.com/SebastianNiemann/Mantella/blob/master/.travis.yml
