source "https://supermarket.chef.io"

metadata

cookbook 'raspberry-pi', git: 'https://github.com/Padgett/chef-raspberry-pi.git'
cookbook 'bitcoin', git: 'https://github.com/facastagnini/chef-bitcoin.git', branch: "patch-1"
