name             'raspberry-bitcoin'
maintainer       'Federico Castagnini'
maintainer_email 'federico.castagnini@gmail.com'
license          'Apache v2.0'
description      'Installs/Configures bitcoin core on a raspberry pi B 2'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.2.0'
issues_url       'https://github.com/facastagnini/raspberry-bitcoin/issues'
source_url       'https://github.com/facastagnini/raspberry-bitcoin'

depends 'apt'
depends 'locale'
# depends 'timezone_lwrp'
depends 'ntp'
depends 'raspberry-pi'
depends 'bitcoin'
